export { default as HomeScreen } from './HomeScreen'
export { default as PatientScreen } from './PatientScreen'
export { default as AddPatientScreen } from './AddPatientScreen'
export { default as PatientsListScreen } from './PatientsListScreen'
export { default as AddAppointmentScreen } from './AddAppointmentScreen'
export { default as EditPatientScreen } from './EditPatientScreen'
